### ISSUE TITLE
requirements broken with creating new environment after import project

### ISSUE THREAD

**Issue by alexsok-bit** [meanmail-dev/requirements#63]
**Describe the bug**
When importing a project into an IDE, for example from a VCS, PyCharm prompts you to create a virtual environment. He creates the environment itself, but cannot add dependencies. For some reason, instead of `pip install -r /path/to/requiremets.txt`, it runs `pip install -e /project/path` and says that I need `setup.py`.

**To Reproduce**

1. start PyCharm
2. create new project `pure python`. with creating virtual environment. select `create main.py`
3. open terminal (`Alt+F12`). and execute follow command `pip install requests`
4. execute follow `pip freeze > requirements.txt`
5. Open settings (`Ctrl+Alt+S`) , follow Project: <project name> -> python interpreter.
6. and open list of all environments and remove (tap minus on a top) project environment
6. follow File -> Close project
7. you shall see the project list window. find your new project and hover your mouse cursor on it, you will see the gear, tap on it and tap `Remove from recent projects`
8 close PyCharm
9. remove virtual environment from disk
10. open PyCharm 
11. tap `Open` and select we project.
12. after indexing will done you will see window with setup new environment, tap `Ok`.
13. wait and see the error window

**Expected behavior**
`pip install -r /path/to/requirements.txt` instead

**Screenshots**
![Setup Environment](https://file.knok.xyz/wYWqu/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202021-04-26%2007-39-40.png)
![Error](https://file.knok.xyz/gDobd/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202021-04-26%2007-36-37.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Licensed to Alexandr Sokolov
Subscription is active until July 2, 2021.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), net.sjrx.intellij.plugins.systemdunitfiles (0.3.2), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), ru.meanmail.plugin.requirements (2021.4-211)
Current Desktop: X-Cinnamon

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
![2021.4-211](https://file.knok.xyz/e81CS/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_024.png)

**Additional context**
[Idea log](https://file.knok.xyz/I6FlI/idea.log)

**Comment by meanmail** [comment]
I'm sorry, but I can't help you. This issue is not related to the plugin. You can create an issue at https://youtrack.jetbrains.com/issues/PY. I am sure your problem will be solved

**Comment by alexsok-bit** [comment]
I already discussed about this problem with PyCharm Support. And the problem disappears if you turn off the plugin.

**Comment by chbndrhnns** [comment]
@meanmail I faced the same problem (not knowing there is an issue already). Just for reference, I reported it [here](https://youtrack.jetbrains.com/issue/PY-57538).

When the Requirements plugin is disabled, PyCharm does not display the error message.

**Comment by aresler** [comment]
PyCharm generates the following log when reproducing the issue:

```
2022-11-29 21:08:07,994 [ 227306]   WARN - #c.j.p.s.c.PyRequirementsTxtOrSetupPySdkConfiguration - Exception during installing packages
The following command was executed:

pip install -e /Users/Andrey.Resler/aa/test_project01

The exit code: 1
The error output of the command:

Obtaining file:///Users/Andrey.Resler/aa/test_project01

ERROR: file:///Users/Andrey.Resler/aa/test_project01 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Non-zero exit code (1)
	at com.jetbrains.python.packaging.PyPackageManagerImpl.install(PyPackageManagerImpl.java:109)
	at com.jetbrains.python.sdk.configuration.PyRequirementsTxtOrSetupPySdkConfiguration.createVirtualEnv(PyRequirementsTxtOrSetupPySdkConfiguration.kt:145)
	at com.jetbrains.python.sdk.configuration.PyRequirementsTxtOrSetupPySdkConfiguration.createAndAddSdk(PyRequirementsTxtOrSetupPySdkConfiguration.kt:65)
	at com.jetbrains.python.sdk.configuration.PyRequirementsTxtOrSetupPySdkConfiguration.createAndAddSdkForConfigurator(PyRequirementsTxtOrSetupPySdkConfiguration.kt:47)
	at com.jetbrains.python.PythonSdkConfigurator$configureSdk$7.invoke(PythonSdkConfigurator.kt:148)
	at com.jetbrains.python.PythonSdkConfigurator$configureSdk$7.invoke(PythonSdkConfigurator.kt:40)
	at com.jetbrains.python.sdk.configuration.PyProjectSdkConfiguration.setSdkUsingExtension(PyProjectSdkConfiguration.kt:54)
	at com.jetbrains.python.PythonSdkConfigurator.configureSdk(PythonSdkConfigurator.kt:148)
	at com.jetbrains.python.PythonSdkConfigurator.access$configureSdk(PythonSdkConfigurator.kt:40)
	at com.jetbrains.python.PythonSdkConfigurator$configureProject$2$1.run(PythonSdkConfigurator.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It shouldn't run `pip install -e` for projects that doesn't have neither 'setup.py' nor 'pyproject.toml', so the issue is probably in the plugin.
